version: 13
port: 5432

default_database:
  name: postgres
  user: postgres
  password: postgres

users:
  - name: postgres
    password: postgres

databases:
  - name: cars
    user: postgres

  - name: rental
    user: postgres

  - name: payment
    user: postgres

resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi